### ISSUE TITLE
Problems building freak on ubuntu.

### ISSUE THREAD

**Issue by ghost** [kikohs/freak#2]
Hello,

I'm attempting to build the freak demo on an ubuntu server.

Ubuntu Version: Lucid (patched/up-to-date)
Cmake version: 2.8.1
OpenCV version:  2.4.9

I'm seeing the following error after invoking make:

mbogucki@motoko:~/Arcanus/VR/Software/OpenCV_FREAK/build$ cmake -DCMAKE_INSTALL_PREFIX=~/Arcanus/VR/Software/OpenCV_FREAK/build/ -DOpenCV_DIR=~/Arcanus/VR/Software/opencv/ ..
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/build
mbogucki@motoko:~/Arcanus/VR/Software/OpenCV_FREAK/build$ make clean
mbogucki@motoko:~/Arcanus/VR/Software/OpenCV_FREAK/build$ make
Scanning dependencies of target freak
[ 33%] Building CXX object src/CMakeFiles/freak.dir/freak.cpp.o
In file included from /home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:50:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.h:41: error: redefinition of ‘class cv::FREAK’
/usr/local/include/opencv2/features2d/features2d.hpp:319: error: previous definition of ‘class cv::FREAK’
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In constructor ‘cv::FREAK::FREAK(bool, bool, float, int, const std::vector<int, std::allocator<int> >&)’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:662: error: class ‘cv::FREAK’ does not have any field named ‘impl’
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In destructor ‘virtual cv::FREAK::~FREAK()’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:668: error: ‘impl’ was not declared in this scope
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In member function ‘virtual void cv::FREAK::computeImpl(const cv::Mat&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:677: error: ‘impl’ was not declared in this scope
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In member function ‘std::vector<int, std::allocator<int> > cv::FREAK::selectPairs(const std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >, std::allocator<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> > > >&, double, bool)’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:683: error: ‘impl’ was not declared in this scope
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: At global scope:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:695: error: no ‘void cv::FREAK::read(const cv::FileNode&)’ member function declared in class ‘cv::FREAK’
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:696: error: no ‘void cv::FREAK::write(cv::FileStorage&) const’ member function declared in class ‘cv::FREAK’
make[2]: **\* [src/CMakeFiles/freak.dir/freak.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/freak.dir/all] Error 2
make: **\* [all] Error 2

Any Suggestions would be very helpful. 
Thank you.

--Mike

**Comment by kikohs** [comment]
Hello,

FREAK has been successfully integrated in OpenCV 2.4.2.
Therefore you don't need the code on github anymore.
Use cv::FREAK instead.

Cheers,

Kikohs

On 9 août 2012, at 20:41, "mwbogucki" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I'm attempting to build the freak demo on an ubuntu server.

Ubuntu Version: Lucid (patched/up-to-date)
Cmake version: 2.8.1
OpenCV version: 2.4.9

I'm seeing the following error after invoking make:

mbogucki@motoko:~/Arcanus/VR/Software/OpenCV_FREAK/build$ cmake -DCMAKE_INSTALL_PREFIX=~/Arcanus/VR/Software/OpenCV_FREAK/build/ -DOpenCV_DIR=~/Arcanus/VR/Software/opencv/ ..
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/build
mbogucki@motoko:~/Arcanus/VR/Software/OpenCV_FREAK/build$ make clean
mbogucki@motoko:~/Arcanus/VR/Software/OpenCV_FREAK/build$ make
Scanning dependencies of target freak
[ 33%] Building CXX object src/CMakeFiles/freak.dir/freak.cpp.o
In file included from /home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:50:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.h:41: error: redefinition of ‘class cv::FREAK’
/usr/local/include/opencv2/features2d/features2d.hpp:319: error: previous definition of ‘class cv::FREAK’
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In constructor ‘cv::FREAK::FREAK(bool, bool, float, int, const std::vector >&)’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:662: error: class ‘cv::FREAK’ does not have any field named ‘impl’
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In destructor ‘virtual cv::FREAK::~FREAK()’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:668: error: ‘impl’ was not declared in this scope
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In member function ‘virtual void cv::FREAK::computeImpl(const cv::Mat&, std::vector >&, cv::Mat&) const’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:677: error: ‘impl’ was not declared in this scope
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: In member function ‘std::vector > cv::FREAK::selectPairs(const std::vector >&, std::vector >, std::allocator > > >&, double, bool)’:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:683: error: ‘impl’ was not declared in this scope
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp: At global scope:
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:695: error: no ‘void cv::FREAK::read(const cv::FileNode&)’ member function declared in class ‘cv::FREAK’
/home/mbogucki/Arcanus/VR/Software/OpenCV_FREAK/src/freak.cpp:696: error: no ‘void cv::FREAK::write(cv::FileStorage&) const’ member function declared in class ‘cv::FREAK’
make[2]: **\* [src/CMakeFiles/freak.dir/freak.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/freak.dir/all] Error 2
make: **\* [all] Error 2

Any Suggestions would be very helpful.
Thank you.

--Mike

**Comment by ghost** [comment]
Hello Kikohs,
Thank you very much. That certainly made things easier ^_^ 
Much appreciated.
--Mike
